name: Android CI

on:
  push:
    branches: [ "main" ]
       
  pull_request:
    branches: [ "main" ]




  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write        # 授予推送 tag 的权限
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: 打包
      run: ./gradlew assembleRelease
      
    - name: 下载
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: |
            **/*.apk

    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v6.3.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'moonlight-android-new-v'
          tag_template: 'yy-i'
          previous_tag: 'moonlight-android-new-v25-01'
            
      
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        files: |
            **/*.apk
        generate_release_notes: true
        token: ${{secrets.GITHUB_TOKEN}}
